### ISSUE TITLE
Fix plotting issue caused by a recent PR

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/EnsemblePerturbation#100]
The axis created at

https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/189f323e78fc98c154552267c05cc0ce82e499dc/ensembleperturbation/plotting/surrogate.py#L295-L310

is not initialized by a projection, so it doesn't support `add_feature`, hence the following code added in a recent change breaks the code when trying to plot sensitivities using the example code in the repo.

https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/189f323e78fc98c154552267c05cc0ce82e499dc/ensembleperturbation/plotting/nodes.py#L222-L225

@WPringle did you miss adding any other changes in #93? For example any change in `surrogate.py`'s initialization of the axis, etc.?

**Comment by SorooshMani-NOAA** [comment]
@WPringle can I safely uncomment the `projection` at https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/189f323e78fc98c154552267c05cc0ce82e499dc/ensembleperturbation/plotting/surrogate.py#L295-L297
or not?

**Comment by WPringle** [comment]
@SorooshMani-NOAA Sure. It make have been that I called it after having initialized the projection outside of the function, but suggest to uncomment it.
