### ISSUE TITLE
Internal Data Backup Question

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/EnsemblePerturbation#106]
@WPringle @zacharyburnett we're losing access to some resources on Hera sometime soon, so I was wondering if you remember if there are any files there that I need to backup related to `ensembleperturbation` or in general the paper you wrote on the probabilistic modeling approach?

**Comment by WPringle** [comment]
I don't believe so.. I had many of my files on Argonne machine and also uploaded to Zenodo

**Comment by SorooshMani-NOAA** [comment]
OK, so I'll close this issue, thanks!
