### ISSUE TITLE
Compatibility with Xarray `2023.11.0`

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/EnsemblePerturbation#115]
e.g. update the adcirc.py [script](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/main/ensembleperturbation/parsing/adcirc.py) to change the dimension of subset as follow:
```python
subset = subset.drop_dims("nele")
subset = subset.assign_coords({'element': ele_da})
```

Taken from https://github.com/noaa-ocs-modeling/SurgeTeamCoordination/issues/144#issuecomment-1828676516

**Comment by SorooshMani-NOAA** [comment]
As a quick fix the version can be pinned to e.g. `2023.7.0`

**Comment by FariborzDaneshvar-NOAA** [comment]
@SorooshMani-NOAA thanks for documenting this. I got this error today and the fix was changing xarray version as noted above (`conda install xarray=2023.7.0`).
