### ISSUE TITLE
NaNs in the surrogate model for Florence

### ISSUE THREAD

**Issue by FariborzDaneshvar-NOAA** [noaa-ocs-modeling/EnsemblePerturbation#133]
@WPringle The percentiles file `percentiles.nc` for Florence with 12-hr leadtime has values for 374,602 nodes out of which, almost half of them are NaNs (mostly land nodes, brown dots in the screenshot below). Is it OK to have NaNs? The number NaNs vary among different percentiles. For example, for `quantile=50`, there are 172,012 NaNs, but for `quantile=90` this number drops to 166,912!

![image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/4fd9f7a0-efcb-42cc-a912-86019bcef81a)

Path to the Percentile file on NHC_COLAB_2: `/nhc/hurricanes/florence_2018_OFCL_12hr_korobov_30/setup/ensemble.dir/analyze/linear_k1_p1_n0.025/percentiles.nc`

I'm checking `ds_percentile.sel(source='surrogate',quantile=90).quantiles.values`

**Comment by WPringle** [comment]
That makes sense. The code automatically sets it NaN once the water level is below the allowed minimum depth.
