### ISSUE TITLE
One eigenvalue for ensemble of perturbed tracks on Hercules

### ISSUE THREAD

**Issue by FariborzDaneshvar-NOAA** [noaa-ocs-modeling/EnsemblePerturbation#134]
The K-L expansion is returning only one eigenvalue for nodes from 30 ensembles. This is the case for all 6 leadtimes of three storms (Sandy, Michael, and Harvey) that I ran recently on Hercules! so there should be something with the workflow on Hercules. @SorooshMani-NOAA is there any part of the workflow on Hercules different from what we had on PW? what's your take on this?

**Comment by FariborzDaneshvar-NOAA** [comment]
Here some example results for Sandy
| Sandy, 12hr leadtime | `Sandy, 72hr leadtime |
| --- | --- |
| ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/b55a41fa-397e-4db8-a390-4166f16f5532) | ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/9d166c4a-047d-4d05-bb52-d0ba680c9649) |
| ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/ce59da23-90a8-421b-b77d-95eaeecbb916) | ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/b22651eb-ef64-4cfd-b398-938eedd4978a) |
| ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/c3165614-ff26-40d1-8c45-1a2c3586ca3b) | ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/b07a0e30-2861-48bd-8625-80be80e38253) |
| ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/26a7a383-f886-49fe-a21b-7be01a9336ed) | ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/c9539a66-1551-4445-999e-72be630fc9d9) |

**Comment by SorooshMani-NOAA** [comment]
Just for the sake of documentation: As we discussed this is due to an issue with setup (there's no track!). It stems from not having internet access. I'm looking into modifying the prep code to avoid the internet requirement.

**Comment by FariborzDaneshvar-NOAA** [comment]
As @SorooshMani-NOAA noted, the workflow was not using atmospheric forcing. Thanks to Soroosh for fixing this bug, I re-ran the workflow with updated `prep.sif` image. 
But still getting one eigenvalue! 

Here are comparison of old and new tracks for some scenarios:
| old tracks | new tracks |
| --- | --- | 
| 12-hr | 12-hr |
| ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/7fd41a44-129f-4d59-8295-8ebdaa0f0883) | ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/82f0f2dc-7aeb-410a-9b88-470564d36d9a) |
| 24-hr | 24-hr |
| ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/da39fbdb-e583-440b-93be-85be9e245e02) | ![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/c941aaed-8254-4970-a566-ef70113fe934) |

**Comment by FariborzDaneshvar-NOAA** [comment]
@SorooshMani-NOAA Here are pressure fields for some timesteps of the original track of Sandy with 12hr leadtime, suggesting that there is an issue with the hurricane model!

October 24, 2012, at 19:00
![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/6bd84103-161f-4c2b-9c13-e2236fb21fba)

October 23, 2012, at 18:00 
![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/8520fcdc-5f56-4d2f-8260-8ae7a6ad7abc)

October 22, 2012, at 23:00
![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/5eed2290-84c8-473a-a048-50a9001cb152)


Path to the output on Hercules: `/work2/noaa/nos-surge/shared/nhc_hurricanes/sandy_2012_OFCL_12hr_korobov_30/setup/ensemble.dir/runs/original/outputs/out2d_1.nc`

**Comment by SorooshMani-NOAA** [comment]
@FariborzDaneshvar-NOAA I noticed I get a bunch of these errors:
```
 No nodal points found inside the radius of the last closed isobar (rrp = 0.000 m)
```
in a test run for Florence. Do you see the same/similar thing in your Sandy runs? It should be in `outputs/mirror.out`. I'm not sure if that means we have to modify the track or there's something in the PaHM settings we need to fix.

**Comment by pvelissariou1** [comment]
@FariborzDaneshvar-NOAA I think we have discussed this issue before. I sent the workaround for missing RRP fields by commenting out a couple of if blocks in the PaHM code contained in SCHISM. I think Soroosh implemented it. I'll push the updated modifications to SCHISM. If the hurricane is way outside the domain at the specific time you will get these warnings as wind fields are not calculated in these cases.

**Comment by SorooshMani-NOAA** [comment]
@pvelissariou1 I see, I just remembered you had it in a dev branch. I didn't realized it's still not in the main SCHISM code? When do you think you'll be able to merge the code?

**Comment by SorooshMani-NOAA** [comment]
In any case, I recompiled using the change I got from Takis into my schism fork. I'm now retesting the binaries on Hercules to make sure we get the wind correctly.

**Comment by FariborzDaneshvar-NOAA** [comment]
@SorooshMani-NOAA @pvelissariou1 Thanks for your efforts. The issue is been resolved! PCA is working as expected! Here are example results for Sandy with 48hr leadtime:

![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/ac83388d-fd07-44fc-b9f8-112527a94de0)
![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/2a4645db-3ffd-43aa-8fd4-ed5128a36c11)
![Image](https://github.com/noaa-ocs-modeling/EnsemblePerturbation/assets/132295102/2a306c48-2bbe-4290-9abe-19b3f6f01306)

I will close this ticket then.

**Comment by pvelissariou1** [comment]
@FariborzDaneshvar-NOAA , @SorooshMani-NOAA I have updated PaHM in SCHISM and pushed the changes in the cmmb branch:
``git clone https://github.com/schism-dev/schism.git -b cmmb``
This branch is already synchronized with master and it is up to date.
Could you please try it and see if it compiles and runs as expected?
In my side I saw no issues.
After confirmation of successful runs, I will create a PR.

**Comment by SorooshMani-NOAA** [comment]
@pvelissariou1 thank you. I will recompile binaries using the cmmb branch and run to see what happens. If you don't have a separate ticket I'll close this again after testing your branch.

**Comment by SorooshMani-NOAA** [comment]
@pvelissariou1 I have issues compiling the `cmmb` branch. I'll follow up with you on chat and then summarize findings here

**Comment by SorooshMani-NOAA** [comment]
The `cmmb` branch can be compiled using `BLD_STANDALONE=ON` option when running cmake.
