### ISSUE TITLE
Perturbation with 0 values

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [noaa-ocs-modeling/EnsemblePerturbation#158]
@WPringle I noticed that in some cases, e.g. 3 perturbation, the 2nd vortex perturbation get's 0 values in `json` which results in a track similar to original. Is that intended? 

```
==> florence_2018_b6ee0579-d77d-4c2f-a599-4b19f7e13336/setup/ensemble.dir/track_files/vortex_4_variable_korobov_2.json <==
{
  "cross_track": 0.0,
  "along_track": 0.0,
  "radius_of_maximum_winds_persistent": 0.0,
  "max_sustained_wind_speed": 0.0,
  "weight": 1.0
}
==> florence_2018_ef7d5855-c68f-4421-9d24-473265ef3f70/setup/ensemble.dir/track_files/vortex_4_variable_korobov_2.json <==
{
  "cross_track": 0.0,
  "along_track": 0.0,
  "radius_of_maximum_winds": 0.0,
  "max_sustained_wind_speed": 0.0,
  "weight": 1.0
}
```

**Comment by WPringle** [comment]
@SorooshMani-NOAA Yes, if use `korobov` with odd number of ensembles then the middle member will be all zeros. It makes sense for the zero/original track to be part of the ensemble imo.

**Comment by SorooshMani-NOAA** [comment]
@WPringle what I mean to say is that in this case we have both a "zero" track **and** an "original" track. I need to go back and check but if I remember correctly we take both original and zero track in this case as inputs, so we'll have a weight associated with the zero track, maybe then the right approach is to always do even number ensembles. What do you think?

Just FYI @FariborzDaneshvar-NOAA

**Comment by WPringle** [comment]
@SorooshMani-NOAA The original track was not supposed to be considered part of the ensemble. It was just a reference run. But maybe the workflow you have does something different?

**Comment by SorooshMani-NOAA** [comment]
Oh, OK, I need to check it again then, for some reason I thought it is being considered as a part of ensemble! Thanks!

**Comment by SorooshMani-NOAA** [comment]
You're right, I just noticed here we correctly ignore original:

https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/a2e545b43bf6424c27cfb6cab60217b4c64d9e01/ensembleperturbation/perturbation/atcf.py#L2100-L2117

Which is the same thing we end up calling from the workflow when combining results.
