### ISSUE TITLE
fix track perturbation (all track files are identical)

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [noaa-ocs-modeling/EnsemblePerturbation#33]
@WPringle noticed that the generated tracks are identical, so something is going wrong in the perturbation currently

**Comment by WPringle** [comment]
Ah yes I see that this is the case even for the reference data in this repository. Didn't check that before.
Was definitely working on the original repository though...

**Comment by zacharyburnettNOAA** [comment]
looks like the problem is here:
https://github.com/noaa-ocs-modeling/EnsemblePerturbation/blob/f554e292e214422040818304478baa5fc9d1fc3c/ensembleperturbation/perturbation/atcf.py#L828

there is no `._df` property anymore, I renamed it to be `.dataframe` to be more descriptive
