### ISSUE TITLE
Two columns of atcf file not being written correctly

### ISSUE THREAD

**Issue by WPringle** [noaa-ocs-modeling/EnsemblePerturbation#38]
Recent PR fixed problem of perturbations to the track and Rmax. 
However, there is something happening to two of the last columns during the writing of the file.
This is a comparison of the the "original.22" file for Hurricane Florence between this repo and the Storm-Surge-Mesh-Subsetting repository on the right:
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/21131934/123833670-363fa200-d8cc-11eb-831d-808900137e1a.png">

**Comment by WPringle** [comment]
Looks like this corresponds to DIR and SPEED (of the storm). Not sure if it is really important or not but DIR should be in degrees from 0-359 and SPEED should be 0-999 kts, presumably both integers.

**Comment by zacharyburnettNOAA** [comment]
fixed with 8a91474993bcb9aaaa5a6f9a827e860a2bed1856
