### ISSUE TITLE
`test_besttrack_ensemble` test failing

### ISSUE THREAD

**Issue by WPringle** [noaa-ocs-modeling/EnsemblePerturbation#44]
- The files in the `output` directory did not match those in the `reference` one.

If the `reference` files have not been updated since recent commits, then need to check make sure there is no mistake for the recent commits, assuming it was correct in the old implementation.

**Comment by WPringle** [comment]
@zacharyburnettNOAA

**Comment by zacharyburnettNOAA** [comment]
the newest code seems to fix this problem by updating the dataframe setter and reference files
