### ISSUE TITLE
`along_track` perturbation not being called?

### ISSUE THREAD

**Issue by WPringle** [noaa-ocs-modeling/EnsemblePerturbation#65]
@zacharyburnettNOAA I noticed that the along_track perturbation doesn't seem to be doing anything in the Florence best track example (the model results and the fort.22 for location is same as other perturbations for different along_track and same cross_track). Can please make sure that along_track is being called correctly.

**Comment by WPringle** [comment]
@zacharyburnettNOAA Update is that I tried just doing say 2 variable perturbation to make it simpler:

For some reason I keep getting no difference between `original.22` and `vortex_2_variable_quadrature_1.22` files but I get correct difference between `original.22` and `vortex_2_variable_quadrature_16.22`.

**Comment by WPringle** [comment]
@zacharyburnettNOAA Recent commit #21fef03c7fa fixes this,  alpha < 0 wasn't being implemented correctly.

**Comment by zacharyburnettNOAA** [comment]
added test in 24a3e4153764e0b61574248fc62d4b1e1407255a

**Comment by WPringle** [comment]
@zacharyburnettNOAA I fixed the `along_track`, the perturbation wasn't being convtered to meters for nautical miles.
